In [12]:
#Learning how to sort a list of tuple entries by an entry (e.g 2nd) in the tuple
from operator import itemgetter

items = [(4, 12,3), (2, 1,2), (6, 4,3), (1, 1, 4), (2, 2,1)]
#items.sort()
test = sorted(items)
test2 = sorted(items, key=itemgetter(2))
print items
print test
print test2

[(4, 12, 3), (2, 1, 2), (6, 4, 3), (1, 1, 4), (2, 2, 1)]
[(1, 1, 4), (2, 1, 2), (2, 2, 1), (4, 12, 3), (6, 4, 3)]
[(2, 2, 1), (2, 1, 2), (4, 12, 3), (6, 4, 3), (1, 1, 4)]


In [34]:
weights = [10,20,30,40]
print max(weights)
print min(weights)
print "The weights are: " 
for iweight in range(0,len(weights)):
    print weights[iweight]*2
   
choices = []
for iweight in range(0,len(weights)):
    if min(weights)<weights[iweight]:
        choices.append(weights[iweight])

print choices

40
10
The weights are: 
20
40
60
80
[20, 30, 40]


In [16]:
from operator import itemgetter
items=[("A",2,10),("B",10,2),("C",1,1)] #name, value, price
print items
rank_items=sorted(items, key=itemgetter(2)) #sort based on price
print rank_items

#map(function_to_apply, list_of_inputs)

weights=map(itemgetter(2),rank_items)
choices = []
rejects = []
print weights

for iweight in range(0,len(weights)):
    if weights[iweight]<5:
        choices.append(rank_items[iweight])
    elif weights[iweight]>=5:
        rejects.append(rank_items[iweight])
        
print choices
print rejects
print sum(weights)
print sum(map(itemgetter(2),rank_items))
print sum(map(itemgetter(2),rank_items[0:2]))

subset=rank_items[0:2] #remember that index starts at 0, upper limit is not inclusive
print subset

print rank_items[2]

[('A', 2, 10), ('B', 10, 2), ('C', 1, 1)]
[('C', 1, 1), ('B', 10, 2), ('A', 2, 10)]
[1, 2, 10]
[('C', 1, 1), ('B', 10, 2)]
[('A', 2, 10)]
13
13
3
[('C', 1, 1), ('B', 10, 2)]
('A', 2, 10)


In [46]:
import numpy as np
g=np.zeros((5,5))
g[3,4]=5
print g

x=np.zeros(g.shape)
print x

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  5.]
 [ 0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [90]:
import numpy as np
csv = np.genfromtxt ('dummy_list_subset2.csv', delimiter=",", dtype=None, names=['name',
                                                                                 'club','pos','value','cost'])

print csv
print csv.shape
print csv[1].dtype

prices = csv['cost']

print prices


#print prices[11]

#csv[11]=('Junuzovic', 'Bremen', 'MIT',  4.8, 150)
#print prices[11]

#prices[11]=7850
#print csv[11]

remove=[]
for j in range(0,len(prices)):
    if prices[j]>= 100:
        print j
        remove.append(j)

filt_csv=np.delete(csv,remove,0)
prices2=filt_csv['cost']

print prices2        
print len(filt_csv)

print sum(prices2[0:6:1])
g = np.zeros([len(filt_csv),400])

g[10,360]=100

print g.shape
print max(remove)


print g[10,360]


[('Robben', 'Bayern', 'MIT',  8.5,  84)
 ('M\xd9ller', 'Bayern', 'MIT',  8.5, 247)
 ('Reus', 'Dortmund', 'MIT',  8.5, 128)
 ('Lewandowski', 'Bayern', 'STU',  8.5, 286)
 ('Kie\xa4ling', 'Leverkusen', 'STU',  5. ,  92)
 ('Neuer', 'Bayern', 'TOR',  5. , 198)
 ('Naldo', 'Wolfsburg', 'ABW',  5. ,  66)
 ('Boateng', 'Bayern', 'ABW',  5. ,  91)
 ('Raffael', 'Gladbach', 'STU',  5. , 170)
 ('Caligiuri', 'Wolfsburg', 'MIT',  5. ,  37)
 ('Alaba', 'Bayern', 'ABW',  5. , 119)
 ('Junuzovic', 'Bremen', 'MIT',  4.8, 112)
 ('Drmic', 'HSV', 'STU',  4.8, -10)
 ('Huntelaar', 'Schalke', 'STU',  4.7,  79)
 ('Meier', 'E. Frankfurt', 'STU',  4.5,  72)
 ('Hummels', 'Dortmund', 'ABW',  4.5, 148)
 ('Leno', 'Leverkusen', 'TOR',  4.5, 196)
 ('Sch\xd9rrle', 'Wolfsburg', 'MIT',  4.5,  62)
 ('Draxler', 'Wolfsburg', 'MIT',  4.5,  69)
 ('Rodriguez', 'Wolfsburg', 'ABW',  4.5,  48)]
(20,)
[('name', 'S11'), ('club', 'S12'), ('pos', 'S3'), ('value', '<f8'), ('cost', '<i8')]
[ 84 247 128 286  92 198  66  91 170  37 119 112 -

In [97]:
import numpy as np
import math
csv = np.genfromtxt ('dummy_list_subset2.csv', delimiter=",", dtype=None, names=['name',
                                                                                 'club','pos','value','cost'])

print csv
print csv.shape
print csv[1].dtype

prices = csv['cost']
values = csv['value']

print prices
print values

for i in range(len(values)):
    values[i]=int(math.ceil(values[i]))

print values

print csv[1].dtype

print int(sum(values))

[('Robben', 'Bayern', 'MIT',  8.5,  84)
 ('M\xd9ller', 'Bayern', 'MIT',  8.5, 247)
 ('Reus', 'Dortmund', 'MIT',  8.5, 128)
 ('Lewandowski', 'Bayern', 'STU',  8.5, 286)
 ('Kie\xa4ling', 'Leverkusen', 'STU',  5. ,  92)
 ('Neuer', 'Bayern', 'TOR',  5. , 198)
 ('Naldo', 'Wolfsburg', 'ABW',  5. ,  66)
 ('Boateng', 'Bayern', 'ABW',  5. ,  91)
 ('Raffael', 'Gladbach', 'STU',  5. , 170)
 ('Caligiuri', 'Wolfsburg', 'MIT',  5. ,  37)
 ('Alaba', 'Bayern', 'ABW',  5. , 119)
 ('Junuzovic', 'Bremen', 'MIT',  4.8, 112)
 ('Drmic', 'HSV', 'STU',  4.8, -10)
 ('Huntelaar', 'Schalke', 'STU',  4.7,  79)
 ('Meier', 'E. Frankfurt', 'STU',  4.5,  72)
 ('Hummels', 'Dortmund', 'ABW',  4.5, 148)
 ('Leno', 'Leverkusen', 'TOR',  4.5, 196)
 ('Sch\xd9rrle', 'Wolfsburg', 'MIT',  4.5,  62)
 ('Draxler', 'Wolfsburg', 'MIT',  4.5,  69)
 ('Rodriguez', 'Wolfsburg', 'ABW',  4.5,  48)]
(20,)
[('name', 'S11'), ('club', 'S12'), ('pos', 'S3'), ('value', '<f8'), ('cost', '<i8')]
[ 84 247 128 286  92 198  66  91 170  37 119 112 -